version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.5
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=omsgms
      - MARIADB_DATABASE=omsgms
      - MARIADB_PASSWORD=omsgms
    #volumes:      
      #- ./mariadb:/bitnami/mariadb/data

  myapp:
    tty: true
    image: docker.io/bitnami/laravel:8
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=omsgms
      - DB_DATABASE=omsgms
      - DB_PASSWORD=omsgms
    depends_on:
      - mariadb
    ports:
      - 3006:3000
    volumes:
      - ./laravel:/app
    # privileged: true # Privileged mode could be required to run this container under Windows
